const miracles = {
    antigoTestamento: [
        { "data-ref": "%C3%8Axodo4:6-7", "data-title": "Cura da mão de Moisés", "data-type": "cura-corpo" },
        { "data-ref": "N%C3%BAmeros12:10-15", "data-title": "Cura da lepra de Miriã", "data-type": "cura-corpo" },
        { "data-ref": "N%C3%BAmeros21:4-9", "data-title": "Cura pela serpente de bronze", "data-type": "cura-corpo" },
        { "data-ref": "1Reis13:4-6", "data-title": "Restauração da mão de Jeroboão", "data-type": "cura-corpo" },
        { "data-ref": "1Reis17:17-24", "data-title": "Ressurreição do filho da viúva de Sarepta", "data-type": "cura-corpo,restauracao-financeira", "data-time": "Durante a seca, após a provisão inicial de alimento" },
        { "data-ref": "2Reis4:38-41", "data-title": "Cura do ensopado mortal", "data-type": "cura-corpo" },
        { "data-ref": "2Reis4:18-37", "data-title": "Ressurreição do filho da sunamita", "data-type": "cura-corpo" },
        { "data-ref": "2Reis5:1-14", "data-title": "Cura da lepra de Naamã", "data-type": "cura-corpo" },
        { "data-ref": "2Reis20:1-11", "data-title": "Cura de Ezequias", "data-type": "cura-corpo" },
        { "data-ref": "2Reis13:20-21", "data-title": "Ressurreição pelo toque nos ossos de Eliseu", "data-type": "cura-corpo" },
        { "data-ref": "1Reis17:8-16", "data-title": "Provisão para a viúva de Sarepta", "data-type": "restauracao-financeira", "data-time": "Durante o período de seca, enquanto durou a farinha e o azeite" },
        { "data-ref": "2Reis4:1-7", "data-title": "Multiplicação do azeite da viúva", "data-type": "restauracao-financeira", "data-time": "Em um único dia, suficiente para pagar dívidas e sustento posterior" },
        { "data-ref": "%C3%8Axodo12:35-36", "data-title": "Israelitas recebem bens dos egípcios", "data-type": "restauracao-financeira", "data-time": "Na noite da saída do Egito, compensação por anos de escravidão" },
        { "data-ref": "%C3%8Axodo16:1-36", "data-title": "Maná e codornizes do céu", "data-type": "restauracao-financeira", "data-time": "Diariamente durante 40 anos no deserto" },
        { "data-ref": "2Reis8:1-6", "data-title": "Restauração das propriedades da sunamita", "data-type": "restauracao-financeira", "data-time": "Após 7 anos de ausência devido à fome" },
        { "data-ref": "J%C3%B342:10-17", "data-title": "Restauração da fortuna de Jó", "data-type": "restauracao-financeira", "data-time": "Após o período de provação, dobrando sua riqueza anterior" }
    ],
    novoTestamento: [
        { "data-ref": "Mateus8:2-4", "data-title": "Cura do leproso", "data-type": "cura-corpo" },
        { "data-ref": "Mateus8:5-13", "data-title": "Cura do servo do centurião", "data-type": "cura-corpo" },
        { "data-ref": "Mateus8:14-15", "data-title": "Cura da sogra de Pedro", "data-type": "cura-corpo" },
        { "data-ref": "Mateus8:16-17", "data-title": "Cura de muitos possessos e enfermos em Cafarnaum", "data-type": "cura-corpo" },
        { "data-ref": "Mateus9:1-8", "data-title": "Cura do paralítico em Cafarnaum", "data-type": "cura-corpo" },
        { "data-ref": "Mateus12:9-14", "data-title": "Cura do homem com a mão ressequida", "data-type": "cura-corpo" },
        { "data-ref": "Mateus9:20-22", "data-title": "Cura da mulher com hemorragia", "data-type": "cura-corpo" },
        { "data-ref": "Mateus9:18-26", "data-title": "Cura da filha de Jairo", "data-type": "cura-corpo" },
        { "data-ref": "Mateus9:27-31", "data-title": "Cura de dois cegos", "data-type": "cura-corpo" },
        { "data-ref": "Mateus9:32-34", "data-title": "Cura do mudo possuído por demônio", "data-type": "cura-corpo" },
        { "data-ref": "Jo%C3%A3o5:1-15", "data-title": "Cura do paralítico junto ao tanque de Betesda", "data-type": "cura-corpo" },
        { "data-ref": "Marcos8:22-26", "data-title": "Cura do cego em Betsaida", "data-type": "cura-corpo" },
        { "data-ref": "Lucas13:10-17", "data-title": "Cura de uma mulher encurvada", "data-type": "cura-corpo" },
        { "data-ref": "Lucas14:1-6", "data-title": "Cura do homem com hidropisia", "data-type": "cura-corpo" },
        { "data-ref": "Lucas17:11-19", "data-title": "Cura dos dez leprosos", "data-type": "cura-corpo" },
        { "data-ref": "Mateus20:29-34", "data-title": "Cura do cego Bartimeu", "data-type": "cura-corpo" },
        { "data-ref": "Jo%C3%A3o9:1-12", "data-title": "Cura do cego de nascença", "data-type": "cura-corpo" },
        { "data-ref": "Lucas22:49-51", "data-title": "Cura da orelha do servo do sumo sacerdote", "data-type": "cura-corpo" },
        { "data-ref": "Atos3:1-10", "data-title": "Pedro cura o coxo no templo", "data-type": "cura-corpo" },
        { "data-ref": "Atos5:12-16", "data-title": "Muitos curados pelos apóstolos", "data-type": "cura-corpo" },
        { "data-ref": "Atos8:6-8", "data-title": "Filipe cura muitos em Samaria", "data-type": "cura-corpo" },
        { "data-ref": "Atos9:17-18", "data-title": "Ananias cura a cegueira de Paulo", "data-type": "cura-corpo" },
        { "data-ref": "Atos9:32-35", "data-title": "Pedro cura Eneas", "data-type": "cura-corpo" },
        { "data-ref": "Atos9:36-42", "data-title": "Pedro ressuscita Tabita", "data-type": "cura-corpo" },
        { "data-ref": "Atos14:8-10", "data-title": "Paulo cura um coxo em Listra", "data-type": "cura-corpo" },
        { "data-ref": "Atos19:11-12", "data-title": "Milagres por meio de Paulo em Éfeso", "data-type": "cura-corpo" },
        { "data-ref": "Atos20:9-12", "data-title": "Paulo ressuscita Êutico", "data-type": "cura-corpo" },
        { "data-ref": "Atos28:3-6", "data-title": "Paulo ileso da picada de víbora", "data-type": "cura-corpo" },
        { "data-ref": "Atos28:7-9", "data-title": "Paulo cura o pai de Públio e outros em Malta", "data-type": "cura-corpo" },
        { "data-ref": "Jo%C3%A3o2:1-11", "data-title": "Transformação de água em vinho em Caná", "data-type": "restauracao-financeira", "data-time": "Instantaneamente durante as bodas" },
        { "data-ref": "Lucas5:1-11", "data-title": "Pesca milagrosa de Pedro", "data-type": "restauracao-financeira", "data-time": "Em um único lançamento de rede após uma noite sem pesca" },
        { "data-ref": "Mateus14:13-21", "data-title": "Alimentação dos cinco mil", "data-type": "restauracao-financeira", "data-time": "Imediatamente com cinco pães e dois peixes" },
        { "data-ref": "Mateus15:32-39", "data-title": "Alimentação dos quatro mil", "data-type": "restauracao-financeira", "data-time": "Imediatamente com sete pães e alguns peixes" },
        { "data-ref": "Mateus17:24-27", "data-title": "Moeda na boca do peixe para o imposto", "data-type": "restauracao-financeira", "data-time": "Imediatamente ao pescar o primeiro peixe" },
        { "data-ref": "Jo%C3%A3o21:1-14", "data-title": "Pesca milagrosa após a ressurreição", "data-type": "restauracao-financeira", "data-time": "Em um único lançamento de rede após uma noite sem pesca" }
    ]
};
